### ISSUE TITLE
Some issue when displaying the text

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/Minori_EN_MOD#1]
I have only tested on Ef first tale
This is in the script
![image](https://user-images.githubusercontent.com/81801486/227922650-e5423c3a-1a28-42a7-8dfa-fda8b8aa15b5.png)
and this is in game
![image](https://user-images.githubusercontent.com/81801486/227922930-0fd6e1fa-dbba-496a-b355-d2fcaa0877a9.png)
It seems like it still can't detect characters has `` and ° such as: げぐごぱぽ

**Comment by Dir-A** [comment]
I forgot to change the second parameter of MultiByteToWideChar,
 it should be fine now, just need to re-download and compile
![QQ截图20230328002319](https://user-images.githubusercontent.com/79064817/228003815-4fca7bb1-2eb5-4ff3-a1c0-00bd58d1da10.png)

**Comment by Cosetto** [comment]
Marvelous!
