### ISSUE TITLE
Request for EN2JP for Steam version of Eden

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/Minori_EN_MOD#2]
I tried copying the code from EN2CN (I'm not sure if that is steam version or not), but the game didn't run.
Also, I think TDA libraries are better here.
![image](https://github.com/Dir-A/Minori_EN_MOD/assets/81801486/e4f6b139-52fa-40cc-9bb0-3e9e4423f2b2)
[Game link](https://drive.google.com/file/d/192jApSTi3U0ZXQXiInXamS7i08Z4zE14/view?usp=sharing)

**Comment by Dir-A** [comment]
Busy for now, I'll check it next week

**Comment by Cosetto** [comment]
Bro, is it possible to implement hook font from directory in Ria Library?

**Comment by Dir-A** [comment]
https://github.com/Dir-A/Minori_EN_MOD/tree/main/src/Eden_EN2JP

can be implemented.
It's midnight. I'll try tomorrow.

**Comment by Cosetto** [comment]
Thank you. I'll close this one then.
An example [hook code](https://github.com/arcusmaximus/VNTranslationTools/blob/36fbe909d02f2e9bb187443e03e2df595f56bfec/VNTextProxy/Proportionalizer.cpp#L86-L123) for CustomFontLoad

**Comment by Cosetto** [comment]
Thanks bro, but which one should I include to [this](https://github.com/Dir-A/Minori_EN_MOD/tree/main/lib/RxHook/src)?

**Comment by Dir-A** [comment]
I didn't get your point.
Maybe you should have been clearer.

**Comment by Cosetto** [comment]
Right, sorry. It's the function to "load font" from directory, which files in RiaLibrary should I add to this repos?

**Comment by Dir-A** [comment]
just use winapi 
load font via game directory
```C
// Load Font When Game Start
// Able to carry Path
::AddFontResourceExW(L"SourceHanSansSC-Heavy.otf", FR_PRIVATE, NULL);
```
https://github.com/Dir-A/Minori_EN_MOD/blob/main/src/Eden_EN2JP/dllmain.cpp#L99

```C
// Param1:Charset (0x80->SJIS), Param2:Font Name (Not Font File Name!)
RxHook::HookCreateFontA(0x80, "思源黑体 Heavy"); 
```
https://github.com/Dir-A/Minori_EN_MOD/blob/main/src/Eden_EN2JP/dllmain.cpp#L67

```C
// When Game Exits Remove Font
::RemoveFontResourceExW(L"SourceHanSansSC-Heavy.otf", FR_PRIVATE, NULL);
```
https://github.com/Dir-A/Minori_EN_MOD/blob/main/src/Eden_EN2JP/dllmain.cpp#L108C14-L108C14

**Comment by Cosetto** [comment]
Thanks
